name: Build all-in-one

on:
  push:
    branches: [main]

permissions:
  contents: write

env:
  JAEGER_VERSION: v1.58.1

jobs:
  all-in-one:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode:
        # - name: v1
        #   binary: all-in-one
        #   skip_sampling: false
        - name: v2
          binary: jaeger
          skip_sampling: true

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        submodules: recursive
        fetch-tags: TRUE

    - run: |
        (cd jaeger && git fetch --tags)
        (cd jaeger && git tag -l)
        (cd jaeger && git status)
        echo "JAEGER_TAG=$(cd jaeger && git describe --tag)" > ${GITHUB_ENV}

    - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version: 1.22.x
        cache-dependency-path: jaeger/go.sum

    - name: Get Node.js version from jaeger-ui
      shell: bash
      run: |
        echo "JAEGER_UI_NODE_JS_VERSION=$(cat jaeger/jaeger-ui/.nvmrc)" >> ${GITHUB_ENV}

    - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: ${{ env.JAEGER_UI_NODE_JS_VERSION }}
        cache: 'yarn'
        cache-dependency-path: jaeger/jaeger-ui/yarn.lock

    - name: Build UI
      run: make -C jaeger build-ui

    - name: Build binary
      working-directory: jaeger
      run: env GOOS=linux GOARCH=arm go build -v -tags=ui -o jaeger-armhf ./cmd/jaeger

    - uses: actions/upload-artifact@v4
      with:
        name: jaeger-armhf
        path: ./jaeger/jaeger-armhf
        overwrite: true

    # - uses: pipe-cd/actions-gh-release@v2
    #   if: github.ref == 'refs/heads/main'
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     name: jaeger-${{ env.JAEGER_TAG }}
    #     title: jaeger-${{ env.JAEGER_TAG }}

    - name: Create tag
      if: github.ref == 'refs/heads/main'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/jaeger-${{ env.JAEGER_TAG }}',
            sha: context.sha
          }).catch(err => {
            if (err.status !== 422) throw err;
            /* already exists, update */
            github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/jaeger-${{ env.JAEGER_TAG }}',
              sha: context.sha
            });
          })

    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref == 'refs/heads/main'
      with:
        files: ./jaeger/jaeger-armhf
        name: jaeger-${{ env.JAEGER_TAG }}
        tag_name: "jaeger-${{ env.JAEGER_TAG }}"
        fail_on_unmatched_files: true
